using Microsoft.EntityFrameworkCore;
using PonyUpPerformance.Web.Data;

namespace PonyUpPerformance.Web.Services;

public sealed class BetaAccessBootstrapService :
    IHostedService
{
    private readonly IServiceScopeFactory _scopeFactory;
    private readonly IConfiguration _configuration;

    public BetaAccessBootstrapService(
        IServiceScopeFactory scopeFactory,
        IConfiguration configuration)
    {
        _scopeFactory = scopeFactory;
        _configuration = configuration;
    }

    public async Task StartAsync(
        CancellationToken cancellationToken)
    {
        await using AsyncServiceScope scope =
            _scopeFactory.CreateAsyncScope();

        ApplicationDbContext db =
            scope.ServiceProvider
                .GetRequiredService<ApplicationDbContext>();

        if (!db.Database.IsRelational())
        {
            return;
        }

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "BetaAccessCodes"
            (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "CodeHash" text NOT NULL,
                "CreditsGranted" integer NOT NULL DEFAULT 5,
                "MaxRedemptions" integer NOT NULL DEFAULT 10,
                "RedemptionCount" integer NOT NULL DEFAULT 0,
                "IsActive" boolean NOT NULL DEFAULT TRUE,
                "ExpiresOn" timestamp with time zone NULL,
                "CreatedOn" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_BetaAccessCodes_CodeHash"
            ON "BetaAccessCodes" ("CodeHash");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "BetaAccessRedemptions"
            (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "BetaAccessCodeId" integer NOT NULL,
                "UserId" text NOT NULL,
                "CreditsGranted" integer NOT NULL DEFAULT 0,
                "RedeemedOn" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_BetaAccessRedemptions_Code_User"
            ON "BetaAccessRedemptions" ("BetaAccessCodeId", "UserId");
            """,
            cancellationToken);

        string configuredCode =
            _configuration["BetaAccess:Code"]
            ?? string.Empty;

        if (string.IsNullOrWhiteSpace(
                configuredCode))
        {
            return;
        }

        int credits =
            int.TryParse(
                _configuration["BetaAccess:Credits"],
                out int configuredCredits)
                ? Math.Clamp(
                    configuredCredits,
                    1,
                    100)
                : 5;

        int maxRedemptions =
            int.TryParse(
                _configuration["BetaAccess:MaxRedemptions"],
                out int configuredMax)
                ? Math.Clamp(
                    configuredMax,
                    1,
                    1000)
                : 10;

        string codeHash =
            BetaAccessCodeService.HashCode(
                BetaAccessCodeService.NormalizeCode(
                    configuredCode));

        await db.Database.ExecuteSqlInterpolatedAsync(
            $"""
            INSERT INTO "BetaAccessCodes"
                ("CodeHash",
                 "CreditsGranted",
                 "MaxRedemptions",
                 "RedemptionCount",
                 "IsActive",
                 "CreatedOn")
            VALUES
                ({codeHash},
                 {credits},
                 {maxRedemptions},
                 0,
                 TRUE,
                 CURRENT_TIMESTAMP)
            ON CONFLICT ("CodeHash")
            DO UPDATE SET
                "CreditsGranted" = EXCLUDED."CreditsGranted",
                "MaxRedemptions" = EXCLUDED."MaxRedemptions",
                "IsActive" = TRUE;
            """,
            cancellationToken);
    }

    public Task StopAsync(
        CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }
}
