using Microsoft.EntityFrameworkCore;
using PonyUpPerformance.Web.Data;

namespace PonyUpPerformance.Web.Services;

public sealed class VinHistoryBootstrapService :
    IHostedService
{
    private readonly IServiceScopeFactory _scopeFactory;

    public VinHistoryBootstrapService(
        IServiceScopeFactory scopeFactory)
    {
        _scopeFactory = scopeFactory;
    }

    public async Task StartAsync(
        CancellationToken cancellationToken)
    {
        await using AsyncServiceScope scope =
            _scopeFactory.CreateAsyncScope();

        ApplicationDbContext db =
            scope.ServiceProvider
                .GetRequiredService<ApplicationDbContext>();

        if (!db.Database.IsRelational())
        {
            return;
        }

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "UserVinHistories"
            (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" text NOT NULL,
                "Vin" text NOT NULL,
                "Year" integer NULL,
                "Make" text NOT NULL DEFAULT '',
                "Model" text NOT NULL DEFAULT '',
                "LastUsedOn" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserVinHistories_UserId_Vin"
            ON "UserVinHistories" ("UserId", "Vin");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_UserVinHistories_UserId_LastUsedOn"
            ON "UserVinHistories" ("UserId", "LastUsedOn" DESC);
            """,
            cancellationToken);
    }

    public Task StopAsync(
        CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }
}
